
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const COMPANY_LOGIN_SUCCESS = "COMPANY_LOGIN_SUCCESS";
export const COMPANY_LOGIN_FAIL = "COMPANY_LOGIN_FAIL";
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const RESULT_SUCCESS = "RESULT_SUCCESS";
export const RESULT_FAIL = "RESULT_FAIL";

